### PR TITLE
InfluxDB: support non-ASCII symbols in sensor names

### PR DESCRIPTION
**Pull request by mstrinzha**

### CODE REVIEW

**Comment by avollkopf** [comment]
Somebody needs to prove first, if this is also working on influxcloud and oss as it has been introduced for that via pull request in the past

**Comment by avollkopf** [comment]
To be more specific. It got introduced with this commit https://github.com/PiBrewing/craftbeerpi4/commit/f8024f3b49902bcb300629fddf831be2b303a931 by @pascal1404

**Comment by mstrinzha** [comment]
I have a lot of  errors in log without my fix:

`InfluxDB write Error: 'latin-1' codec can't encode characters`.

The error is thrown by urllib3, not influxdb.
Influxdb-1.8 OSS edition works fine with the fix.

**Comment by avollkopf** [comment]
> I have a lot of errors in log without my fix:
> 
> `InfluxDB write Error: 'latin-1' codec can't encode characters`.
> 
> The error is thrown by urllib3, not influxdb. Influxdb-1.8 OSS edition works fine with the fix.

I am sure it'll work with 1.8 but I am talking about cloud and 2.0+ which is handled from line 67 to 74. Lines 60 to 65 got introduced with the PR mentioned above in particular for cloud and OSS 2.0+. Removing them might negatively interfere with the old PR. Therefore, we need to wait for the feedback from @pascal1404

**Comment by mstrinzha** [comment]
Oh, I see. I prepare first commit from old repository and lost cloud changes.
Fixed for InfluxDB Cloud too.

**Review by pascal1404 — APPROVED** [review]
It works with influxdb-cloud. For me it can be added.

**Pull request merged**
